"""Catálogo Canónico de Indicadores Institucionales BICU.

Fase 29.19.1–29.19.2 — Auditoría e Implementación Controlada de Indicadores.

Contiene las definiciones metodológicas certificadas en Fase 29.19 §7 y §8.
"""

from typing import Dict, List, Optional

from app.indicators.domain.contracts import (
    IndicatorCategory,
    IndicatorDefinition,
    IndicatorId,
)


_DEFINITIONS: List[IndicatorDefinition] = [
    IndicatorDefinition(
        indicator_id=IndicatorId.IND_ACT_01,
        name="Total de Actividades Planificadas en el POA",
        category=IndicatorCategory.ACTIVIDAD,
        definition="Número total de actividades formalmente registradas en el módulo de planificación institucional para un período dado.",
        purpose="Medir la magnitud y carga de trabajo proyectada por las áreas universitarias de BICU.",
        source="planning_planned_activities (Esquema V003)",
        numerator="COUNT(activity_internal_id)",
        denominator=None,
        formula="COUNT(activity_internal_id)",
        unit="actividades",
        periodicity="Anual, Semestral, Trimestral",
        dimensions=["sede", "programa", "eje_estrategia", "tipo_evento", "area_responsable"],
        null_policy="activity_internal_id nunca es nulo. Si fecha_evento es nula, se agrupa bajo 'Sin Fecha en POA' sin excluir del conteo.",
        duplicate_policy="activity_internal_id garantiza unicidad física. planning_id único por restricción de esquema.",
        limitations="No refleja si la actividad fue aprobada metodológicamente ni si fue ejecutada.",
        allowed_interpretation="La universidad proyectó K actividades en el período evaluado.",
        forbidden_interpretation="Afirmar que las K actividades se realizaron o contaron con presupuesto ejecutado.",
    ),
    IndicatorDefinition(
        indicator_id=IndicatorId.IND_ACT_02,
        name="Total de Eventos y Actividades Efectivamente Ejecutadas",
        category=IndicatorCategory.ACTIVIDAD,
        definition="Conteo de actividades institucionales reales concluidas y respaldadas por documentación técnica consolidada.",
        purpose="Conocer el volumen real de acción territorial y extensión universitaria llevado a cabo.",
        source="actividad (Esquemas V001/V002)",
        numerator="COUNT(id_actividad) WHERE estado IN ('EJECUTADA', 'REPORTADA', 'CERRADA')",
        denominator=None,
        formula="COUNT(id_actividad) WHERE estado IN ('EJECUTADA', 'REPORTADA', 'CERRADA')",
        unit="actividades",
        periodicity="Semanal, Mensual, Trimestral, Anual",
        dimensions=["sede", "departamento_geo", "municipio", "tipo_evento", "programa"],
        null_policy="sede obligatoria por CHECK DDL. Registros con fecha_inicio nula no se reportan en períodos cerrados.",
        duplicate_policy="Protegido por hash_sha256 inmutable de actividad. Reprocesamientos no incrementan el conteo.",
        limitations="No indica si la actividad cumplió sus objetivos cualitativos o si tuvo vínculo con el POA.",
        allowed_interpretation="BICU ejecutó y documentó formalmente M actividades en el territorio durante el período.",
        forbidden_interpretation="Asumir que todas las actividades ejecutadas provienen de una planificación formal.",
    ),
    IndicatorDefinition(
        indicator_id=IndicatorId.IND_ACT_03,
        name="Total de Actividades Emergentes",
        category=IndicatorCategory.ACTIVIDAD,
        definition="Conteo de actividades ejecutadas que no cuentan con planificación previa formal o poseen bandera es_emergente=1.",
        purpose="Medir el volumen de respuesta universitaria ante demandas comunitarias y contingencias territoriales no programadas.",
        source="actividad (V001/V002) y planning_execution_links (V004)",
        numerator="COUNT(id_actividad) WHERE es_emergente = 1 OR NOT EXISTS(link ACTIVE)",
        denominator=None,
        formula="COUNT(id_actividad) WHERE es_emergente = 1 OR id_actividad NOT IN (SELECT id_actividad FROM planning_execution_links WHERE link_status = 'ACTIVE')",
        unit="actividades",
        periodicity="Mensual, Trimestral, Anual",
        dimensions=["sede", "departamento_geo", "tipo_evento", "programa"],
        null_policy="Tratamiento estándar de actividad.",
        duplicate_policy="Idempotencia por hash_sha256.",
        limitations="No califica negativamente el esfuerzo; mide acción reactiva o contingente.",
        allowed_interpretation="La universidad atendió E actividades extraordinarias fuera del POA.",
        forbidden_interpretation="Concluir que las actividades emergentes son irregulares o carecen de valor institucional.",
    ),
    IndicatorDefinition(
        indicator_id=IndicatorId.IND_ACT_04,
        name="Tasa de Formalización Metodológica",
        category=IndicatorCategory.ACTIVIDAD,
        definition="Porcentaje de actividades planificadas que cuentan con un Diseño Metodológico aprobado.",
        purpose="Evaluar el rigor pedagógico y metodológico en la preparación de las actividades institucionales.",
        source="planning_planned_activities y planning_methodological_designs (V003)",
        numerator="COUNT_DISTINCT(planned_activity_internal_id) WHERE status = 'APPROVED'",
        denominator="COUNT(activity_internal_id) de actividades planificadas",
        formula="(COUNT_DISTINCT(planned_activity_internal_id) / COUNT(activity_internal_id)) * 100",
        unit="%",
        periodicity="Semestral, Anual",
        dimensions=["sede", "programa", "eje_estrategia"],
        null_policy="Planes sin diseño metodológico aportan 0 al numerador.",
        duplicate_policy="Máximo 1 diseño APPROVED por plan garantizado por invariante de dominio.",
        limitations="Tener diseño aprobado no garantiza ejecución exitosa.",
        allowed_interpretation="El X% de las actividades planificadas completó su formalización pedagógica previa.",
        forbidden_interpretation="Afirmar que las actividades con diseño en DRAFT fueron ejecutadas.",
    ),
    IndicatorDefinition(
        indicator_id=IndicatorId.IND_CUMP_01,
        name="Cobertura de Ejecución de Actividades Planificadas",
        category=IndicatorCategory.CUMPLIMIENTO,
        definition="Porcentaje de actividades del POA que cuentan con al menos una ejecución real vinculada y activa en el sistema.",
        purpose="Evaluar la efectividad y cumplimiento operativo de la planificación institucional.",
        source="planning_planned_activities, planning_execution_links y actividad",
        numerator="COUNT_DISTINCT(pel.planning_internal_id) WHERE pel.link_status = 'ACTIVE' AND act.estado IN ('EJECUTADA', 'REPORTADA', 'CERRADA')",
        denominator="COUNT(ppa.activity_internal_id) de actividades planificadas",
        formula="(COUNT_DISTINCT(pel.planning_internal_id) / COUNT(ppa.activity_internal_id)) * 100",
        unit="%",
        periodicity="Semestral, Anual",
        dimensions=["sede", "programa", "eje_estrategia"],
        null_policy="Planes sin vínculo aportan 0 al numerador. Denominador cero retorna None / Indefinido.",
        duplicate_policy="COUNT_DISTINCT en numerador garantiza que multisesiones (1:N) cuenten exactamente como 1 plan cumplido.",
        limitations="Un plan puede estar cubierto al 100% aunque haya tenido menor aforo que la meta programada.",
        allowed_interpretation="El X% de las actividades programadas en el POA registró al menos un evento de ejecución verificable.",
        forbidden_interpretation="El área cumplió el X% de sus metas globales de protagonistas.",
    ),
    IndicatorDefinition(
        indicator_id=IndicatorId.IND_CUMP_02,
        name="Índice de Eficacia de Metas de Participación (Planificado vs Ejecutado)",
        category=IndicatorCategory.CUMPLIMIENTO,
        definition="Razón porcentual entre el total de protagonistas reales atendidos en actividades vinculadas y la meta total comprometida en el plan.",
        purpose="Medir la capacidad de convocatoria y el alcance de las metas cuantitativas de protagonistas.",
        source="planning_planned_activities.participant_goals vs actividad_metrica_agregada / participacion",
        numerator="Sumatoria de participantes reales en actividades con vínculo activo",
        denominator="Sumatoria de metas comprometidas en los planes vinculados asociados",
        formula="(Total Participantes Reales / Meta Total Planificada) * 100",
        unit="%",
        periodicity="Trimestral, Semestral, Anual",
        dimensions=["sede", "programa", "eje_estrategia"],
        null_policy="Si meta total es cero o nula, retorna None / Indefinido.",
        duplicate_policy="Parametrizable por multisession_goal_mode ('COHORT_UNIQUE' vs 'SESSION_SUM').",
        limitations="Sujeto a la decisión institucional sobre agregación de metas multisesión.",
        allowed_interpretation="En las actividades vinculadas al plan se alcanzó el Y% de la meta de asistencia prevista.",
        forbidden_interpretation="Afirmar que el Y% corresponde a personas únicas diferentes a menos que se use la métrica neta.",
    ),
    IndicatorDefinition(
        indicator_id=IndicatorId.IND_PART_01,
        name="Total de Participaciones Registradas (Asistencias Brutas)",
        category=IndicatorCategory.PARTICIPACION,
        definition="Conteo total de registros individuales de asistencia efectiva en las listas oficiales de eventos realizados.",
        purpose="Medir el volumen bruto de servicio y atención educativa brindado por BICU.",
        source="participacion (Esquema V001)",
        numerator="COUNT(id_participacion) WHERE condicion_asistencia = 'PRESENTE' AND es_historico_preexistente = 0",
        denominator=None,
        formula="COUNT(id_participacion) WHERE condicion_asistencia = 'PRESENTE' AND es_historico_preexistente = 0",
        unit="participaciones",
        periodicity="Semanal, Mensual, Trimestral, Anual",
        dimensions=["sede", "tipo_evento", "estamento_declarado", "sexo"],
        null_policy="Registros con condicion_asistencia nula se tratan como ausentes y se excluyen.",
        duplicate_policy="Una persona que asistió a 4 actividades computa legítimamente como 4 participaciones brutas.",
        limitations="NO REPRESENTA PERSONAS ÚNICAS.",
        allowed_interpretation="BICU registró P asistencias en sus actividades formativas y de extensión.",
        forbidden_interpretation="BICU capacitó a P personas distintas en la Costa Caribe.",
    ),
    IndicatorDefinition(
        indicator_id=IndicatorId.IND_PART_02,
        name="Total de Personas Únicas Alcanzadas",
        category=IndicatorCategory.PARTICIPACION,
        definition="Cantidad de personas distintas que participaron al menos una vez en cualquier actividad institucional durante el período.",
        purpose="Medir la cobertura real y la penetración poblacional neta de BICU.",
        source="persona, participacion, actividad (V001)",
        numerator="COUNT_DISTINCT(id_persona_interno) WHERE condicion = 'PRESENTE' AND es_historico = 0 Y con ID verificable",
        denominator=None,
        formula="COUNT_DISTINCT(persona.id_persona_interno) con al menos una asistencia PRESENTE",
        unit="personas únicas",
        periodicity="Trimestral, Semestral, Anual",
        dimensions=["sexo", "sede", "etnia", "municipio_residencia"],
        null_policy="Personas sin cédula ni ID institucional se aíslan en conteo de identidades no verificadas.",
        duplicate_policy="Cada individuo cuenta exactamente 1 vez independientemente de cuántas veces haya participado.",
        limitations="Depende de la disponibilidad de cédula o carné institucional.",
        allowed_interpretation="BICU benefició directamente a U ciudadanos únicos identificados durante el período.",
        forbidden_interpretation="Comparar esta cifra directamente con la suma de M1 sin aclarar que M1 mide asistencias brutas.",
    ),
    IndicatorDefinition(
        indicator_id=IndicatorId.IND_PART_03,
        name="Tasa de Recurrencia de Participantes",
        category=IndicatorCategory.PARTICIPACION,
        definition="Proporción de personas únicas que han asistido a dos o más actividades institucionales distintas dentro del período.",
        purpose="Evaluar la fidelización, el seguimiento formativo continuo y la concentración de la atención universitaria.",
        source="participacion (V001)",
        numerator="COUNT_DISTINCT(id_persona) con COUNT_DISTINCT(id_actividad) >= 2",
        denominator="Total personas únicas participantes en el período (IND-PART-02)",
        formula="(Personas Recurrentes / Total Personas Únicas) * 100",
        unit="%",
        periodicity="Semestral, Anual",
        dimensions=["sede", "estamento_declarado"],
        null_policy="Si total de personas únicas es 0, retorna 0.0%.",
        duplicate_policy="DISTINCT id_actividad asegura que múltiples asistencias a la misma actividad no califiquen como recurrencia.",
        limitations="En períodos cortos (ej. una semana) la tasa tenderá naturalmente a cero.",
        allowed_interpretation="El R% de los beneficiarios de BICU participó en procesos formativos múltiples.",
        forbidden_interpretation="Interpretar baja recurrencia como fracaso en eventos masivos de ciclo único.",
    ),
    IndicatorDefinition(
        indicator_id=IndicatorId.IND_PART_04,
        name="Distribución de Participación por Sexo (Índice de Paridad)",
        category=IndicatorCategory.PARTICIPACION,
        definition="Proporción de mujeres y varones entre los participantes con sexo confirmado y razón de paridad de género.",
        purpose="Garantizar el cumplimiento de las políticas de equidad de género de BICU y compromisos de cooperación.",
        source="persona.sexo vía participacion (V001) y actividad_metrica_agregada (V002)",
        numerator="Mujeres: SUM(sexo='F') | Varones: SUM(sexo='M')",
        denominator="Total participantes con sexo confirmado (F + M)",
        formula="% Femenino = (F / (F + M)) * 100 | % Masculino = (M / (F + M)) * 100 | Paridad = (% Femenino / % Masculino)",
        unit="% y Razón",
        periodicity="Mensual, Trimestral, Anual",
        dimensions=["sede", "tipo_evento", "estamento_declarado"],
        null_policy="Prohibición estricta de imputar sexo. Registros sin sexo se reportan en categoría 'No Especificado'.",
        duplicate_policy="Aplica a asistencias registradas del período.",
        limitations="Si la tasa de no especificados es alta, el indicador puede presentar sesgo.",
        allowed_interpretation="De las participaciones con sexo registrado, el F% correspondió a mujeres.",
        forbidden_interpretation="Asumir que la distribución aplica a las personas con dato no especificado.",
    ),
    IndicatorDefinition(
        indicator_id=IndicatorId.IND_PART_05,
        name="Distribución de Participantes por Estamento",
        category=IndicatorCategory.PARTICIPACION,
        definition="Desglose porcentual de participaciones según el rol institucional declarado (Estudiante, Docente, etc.).",
        purpose="Conocer la composición estamentaria de la comunidad universitaria y externa atendida.",
        source="participacion.estamento_declarado (V001)",
        numerator="Conteo de participaciones por cada estamento",
        denominator="Total participaciones registradas en el período",
        formula="(Participaciones por Estamento / Total Participaciones) * 100",
        unit="%",
        periodicity="Mensual, Trimestral, Anual",
        dimensions=["sede", "tipo_evento", "sexo"],
        null_policy="Estamentos no normalizados o nulos se agrupan en 'COLA_REVISION / Sin Especificar'.",
        duplicate_policy="Conteo sobre asistencias efectivas no históricas.",
        limitations="El estamento es el declarado en el evento, no necesariamente el nombramiento contractual.",
        allowed_interpretation="El E% de las asistencias correspondió a estudiantes regulares.",
        forbidden_interpretation="Concluir el censo laboral de la universidad a partir de listas de eventos.",
    ),
    IndicatorDefinition(
        indicator_id=IndicatorId.IND_TERR_01,
        name="Distribución Territorial de Actividades por Sede",
        category=IndicatorCategory.TERRITORIAL,
        definition="Distribución de la cantidad de actividades ejecutadas entre los recintos y sedes universitarias de BICU.",
        purpose="Medir el grado de desconcentración territorial del quehacer universitario en la Costa Caribe.",
        source="actividad.sede (V001)",
        numerator="COUNT(id_actividad) por cada sede institucional",
        denominator="Total actividades ejecutadas en el período (IND-ACT-02)",
        formula="(Actividades en Sede / Total Actividades) * 100",
        unit="%",
        periodicity="Mensual, Trimestral, Anual",
        dimensions=["sede", "tipo_evento", "programa"],
        null_policy="La sede es obligatoria en el esquema físico (CHECK).",
        duplicate_policy="Basado en actividades ejecutadas únicas por hash.",
        limitations="Mide cantidad de eventos, no necesariamente la duración o inversión financiera por sede.",
        allowed_interpretation="La sede Bilwi concentró el S% de los eventos ejecutados por BICU.",
        forbidden_interpretation="Asumir que mayor cantidad de actividades equivale a mayor impacto pedagógico.",
    ),
    IndicatorDefinition(
        indicator_id=IndicatorId.IND_TRAZ_01,
        name="Índice de Trazabilidad Planificación-Ejecución",
        category=IndicatorCategory.TRAZABILIDAD,
        definition="Porcentaje de actividades ejecutadas que cuentan con un vínculo formal activo hacia el POA.",
        purpose="Medir el grado de disciplina institucional y alineamiento de las acciones de campo con la programación formal.",
        source="actividad (V001) y planning_execution_links (V004)",
        numerator="COUNT_DISTINCT(act.id_actividad) con vínculo ACTIVE en planning_execution_links",
        denominator="Total actividades ejecutadas en el período (IND-ACT-02)",
        formula="(Actividades Trazadas / Total Actividades Ejecutadas) * 100",
        unit="%",
        periodicity="Trimestral, Anual",
        dimensions=["sede", "area_responsable"],
        null_policy="Actividades sin enlace aportan 0 al numerador.",
        duplicate_policy="Enlaces revocados (REVOKED) o reemplazados (SUPERSEDED) se excluyen estrictamente.",
        limitations="Un valor bajo refleja alta actividad emergente, no necesariamente inactividad.",
        allowed_interpretation="El T% de las actividades de campo estuvo formalmente alineado al POA mediante trazabilidad certificada.",
        forbidden_interpretation="Concluir que las actividades no trazadas carecieron de valor institucional.",
    ),
    IndicatorDefinition(
        indicator_id=IndicatorId.IND_TRAZ_02,
        name="Tasa de Discrepancia Documental (M1 vs M2–M5)",
        category=IndicatorCategory.TRAZABILIDAD,
        definition="Porcentaje de actividades procesadas que presentan diferencias numéricas activas entre la Ficha agregada y las listas nominales.",
        purpose="Servir de semáforo de calidad de datos y rigor en la recolección de firmas en territorio.",
        source="discrepancia y actividad (V001)",
        numerator="COUNT_DISTINCT(id_actividad) en discrepancia con estado = 'REQUIERE_REVISION'",
        denominator="Total actividades procesadas en el lote / período",
        formula="(Actividades con Discrepancia Activa / Total Actividades Procesadas) * 100",
        unit="%",
        periodicity="Por lote, Semanal, Mensual",
        dimensions=["sede", "departamento_responsable"],
        null_policy="No aplica.",
        duplicate_policy="COUNT_DISTINCT asegura que múltiples discrepancias en una misma actividad cuenten como 1 actividad discrepante.",
        limitations="Mide consistencia documental interna, no veracidad física del evento.",
        allowed_interpretation="El D% de los informes presentados contiene diferencias entre sus tablas de resumen y sus listas de firmas.",
        forbidden_interpretation="El D% de los informes contiene datos falsificados (la mayoría son omisiones de captura).",
    ),
    IndicatorDefinition(
        indicator_id=IndicatorId.IND_TRAZ_03,
        name="Tasa de Disponibilidad de Cédula Oficial",
        category=IndicatorCategory.CALIDAD,
        definition="Porcentaje de personas participantes que cuentan con número oficial de cédula registrado y válido.",
        purpose="Evaluar la calidad del padrón de beneficiarios y la viabilidad de cálculo de personas únicas.",
        source="persona.cedula (V001)",
        numerator="COUNT_DISTINCT(id_persona_interno) WHERE cedula IS NOT NULL AND TRIM(cedula) != ''",
        denominator="Total personas únicas participantes en el período",
        formula="(Personas con Cédula / Total Personas Únicas) * 100",
        unit="%",
        periodicity="Mensual, Trimestral, Anual",
        dimensions=["sede", "etnia", "estamento_declarado"],
        null_policy="Cédula nula o vacía se cuenta estrictamente en el denominador, no en el numerador.",
        duplicate_policy="Base de personas únicas confirmadas.",
        limitations="En zonas remotas la falta de cédula es un factor estructural poblacional.",
        allowed_interpretation="El C% de los participantes universitarios cuenta con cédula de identidad confirmada en el sistema.",
        forbidden_interpretation="Excluir o desacreditar la asistencia de comunitarios sin documento de identidad.",
    ),
]

INDICATOR_CATALOG: Dict[str, IndicatorDefinition] = {
    d.indicator_id: d for d in _DEFINITIONS
}


class IndicatorCatalog:
    """Acceso al catálogo oficial inmutable de indicadores."""

    @staticmethod
    def get(indicator_id: str) -> Optional[IndicatorDefinition]:
        """Retorna la definición oficial de un indicador por ID."""
        return INDICATOR_CATALOG.get(indicator_id)

    @staticmethod
    def list_all() -> List[IndicatorDefinition]:
        """Retorna todas las definiciones certificadas."""
        return list(INDICATOR_CATALOG.values())

    @staticmethod
    def get_by_category(category: IndicatorCategory) -> List[IndicatorDefinition]:
        """Retorna las definiciones correspondientes a una categoría."""
        return [d for d in INDICATOR_CATALOG.values() if d.category == category]

    @staticmethod
    def contains(indicator_id: str) -> bool:
        """Verifica si un indicador está formalmente registrado."""
        return indicator_id in INDICATOR_CATALOG
