# -*- mode: python ; coding: utf-8 -*-
# =============================================================================
# BICU_Consolidador.spec
# PyInstaller specification file para el Consolidador Institucional de Asistencias
# Fase 14.10 -- Empaquetado Windows
# Actualizado en Fase 29.24.1 -- Backup, Restore y Preflight Operacional
#
# Estrategia: --onedir (mas estable con CustomTkinter, catalogos, templates)
# Python: 3.14.5
# PyInstaller: 6.22.3
#
# USO:
#   pyinstaller BICU_Consolidador.spec
# =============================================================================

from pathlib import Path

# Directorio raiz del proyecto
ROOT = Path(SPECPATH)

block_cipher = None

a = Analysis(
    ['run_consolidator.py'],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[
        (str(ROOT / 'config'), 'config'),
        (str(ROOT / 'templates'), 'templates'),
        (str(ROOT / 'assets'), 'assets'),
    ],
    hiddenimports=[
        'customtkinter',
        'darkdetect',
        'packaging',
        'packaging.version',
        'packaging.specifiers',
        'PIL',
        'PIL.Image',
        'openpyxl',
        'openpyxl.workbook',
        'openpyxl.worksheet',
        'openpyxl.styles',
        'openpyxl.utils',
        'et_xmlfile',
        'docx',
        'docx.oxml',
        'docx.shared',
        'docx.enum',
        'docx.parts',
        'lxml',
        'lxml.etree',
        'pydantic',
        'pydantic_core',
        'yaml',
        'pandas',
        'numpy',
        'dateutil',
        'dateutil.parser',
        'six',
        'app',
        'app.word_consolidator',
        'app.word_consolidator.ui',
        'app.word_consolidator.ui.app',
        'app.word_consolidator.ui.views',
        'app.word_consolidator.ui.views.main_window',
        'app.word_consolidator.ui.views.matrix_selection_view',
        'app.word_consolidator.ui.views.period_selection_view',
        'app.word_consolidator.ui.views.validation_view',
        'app.word_consolidator.ui.views.progress_view',
        'app.word_consolidator.ui.views.result_view',
        'app.word_consolidator.ui.services',
        'app.word_consolidator.ui.services.application_service',
        'app.word_consolidator.ui.services.error_translator',
        'app.word_consolidator.ui.workers',
        'app.word_consolidator.ui.workers.consolidation_worker',
        'app.word_consolidator.pipeline',
        'app.word_consolidator.models',
        'app.word_consolidator.readers',
        'app.word_consolidator.readers.matrix_reader',
        'app.word_consolidator.readers.period_filter',
        'app.word_consolidator.engine',
        'app.word_consolidator.engine.consolidation_engine',
        'app.word_consolidator.engine.discrepancy_detector',
        'app.word_consolidator.document',
        'app.word_consolidator.document.models',
        'app.word_consolidator.document.transformer',
        'app.word_consolidator.document.orchestrator',
        'app.word_consolidator.document.institutional_models',
        'app.word_consolidator.document.institutional_transformer',
        'app.word_consolidator.docx_generator',
        'app.word_consolidator.docx_generator.renderer',
        'app.word_consolidator.docx_generator.style_manager',
        'app.word_consolidator.docx_generator.table_builder',
        'app.word_consolidator.docx_generator.header_footer',
        'app.word_consolidator.docx_generator.page_setup',
        'app.word_consolidator.docx_generator.sections',
        'app.word_consolidator.docx_generator.sections.cover',
        'app.word_consolidator.docx_generator.sections.executive_summary',
        'app.word_consolidator.docx_generator.sections.consolidated_table',
        'app.word_consolidator.docx_generator.sections.activity_cards',
        'app.word_consolidator.docx_generator.sections.demographics',
        'app.word_consolidator.docx_generator.sections.estamentos',
        'app.word_consolidator.docx_generator.sections.territory',
        'app.word_consolidator.docx_generator.sections.quality_audit',
        'app.word_consolidator.docx_generator.sections.conclusions',
        'app.word_consolidator.docx_generator.sections.annexes',
        'app.word_consolidator.institutional_docx',
        'app.word_consolidator.institutional_docx.constants',
        'app.word_consolidator.institutional_docx.page_setup',
        'app.word_consolidator.institutional_docx.table_builder',
        'app.word_consolidator.institutional_docx.evidences_builder',
        'app.word_consolidator.institutional_docx.generator',
        'app.word_consolidator.institutional_docx.spec',
        'app.core',
        'app.core.catalog',
        'app.core.catalog.catalog_loader',
        'app.core.exceptions',
        'app.core.exceptions.system_exceptions',
        'app.audit',
        'app.audit.audit_logger',
        'app.parsers',
        'app.normalization',
        # --- Módulo de Backup/Restore/Preflight (Fase 29.24.1) ---
        'app.backup',
        'app.backup.domain',
        'app.backup.domain.models',
        'app.backup.domain.ports',
        'app.backup.application',
        'app.backup.application.backup_service',
        'app.backup.application.restore_service',
        'app.backup.application.preflight',
        # --- Biblioteca estándar (explícita por compatibilidad PyInstaller) ---
        'ctypes',
        'ctypes.wintypes',
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'threading',
        'queue',
        'uuid',
        'hashlib',
        'shutil',
        'unicodedata',
        'zipfile',
        'tempfile',
        'traceback',
        'logging',
        'logging.handlers',
        'requests',
        'requests.adapters',
        'requests.auth',
        'urllib3',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pytest',
        'pytest_cov',
        '_pytest',
        'coverage',
        'jinja2',
        'matplotlib',
        'scipy',
        'IPython',
        'jupyter',
    ],
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='BICU_Consolidador',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(ROOT / 'assets' / 'bicu_logo.ico'),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='BICU_Consolidador',
)
