"""Capa Application - Sistema Institucional de Gestión de Actividades, Participantes, Evidencias y Reportes (BICU).

Contiene contratos, modelos de intención (Commands), consultas de lectura (Queries),
DTOs de transporte y fakes en memoria para pruebas desacopladas de persistencia.
"""

from app.application.commands import (
    RegistrarActividadCommand,
    AsignarPlanificacionCommand,
    AsignarDisenoMetodologicoCommand,
    RegistrarInformeActividadCommand,
    RegistrarPersonaCommand,
    RegistrarParticipacionIndividualCommand,
    IngestarListaAsistenciaCommand,
    RegistrarEvidenciaDigitalCommand,
    VincularEvidenciaActividadCommand,
    DesvincularEvidenciaActividadCommand,
    CrearInformeSemanalCommand,
    AsociarActividadesInformeSemanalCommand,
    RegistrarDiscrepanciaCommand,
    ResolverRevisionDiscrepanciaCommand,
)
from app.application.commands.calidad_commands import (
    EvaluarCalidadActividadCommand,
)
from app.application.queries import (
    ConsultarActividadesPorPeriodoQuery,
    ObtenerDetalleActividadQuery,
    BuscarPersonasPorNombreQuery,
    ObtenerPersonaPorIdQuery,
    ConsultarParticipantesPorActividadQuery,
    ConsultarParticipantesEnRevisionQuery,
    ConsultarEvidenciasActividadQuery,
    ConsultarInformeSemanalPorPeriodoQuery,
    ConsultarDiscrepanciasPendientesQuery,
)
from app.application.dto import (
    FilaParticipanteIngestaDTO,
    PartidaPresupuestariaDTO,
    DetalleActividadInformeDTO,
    IngestaListaAsistenciaResultDTO,
    ActividadResumenDTO,
    ActividadDetalleDTO,
    PersonaResumenDTO,
    PersonaDetalleDTO,
    ParticipacionDetalleDTO,
    EvidenciaVinculadaDTO,
    DiscrepanciaDetalleDTO,
    InformeSemanalCompletoDTO,
    PlanificacionAsignadaDTO,
    DisenoMetodologicoAsignadoDTO,
    InformeActividadRegistradoDTO,
)
from app.application.dto.quality_dtos import (
    ValidationFindingDTO,
    QualityAssessmentDTO,
)
from app.application.commands.pipeline_commands import (
    EjecutarPipelineActividadCommand,
    ExportarMatricesActividadCommand,
    ExportarMatricesPeriodoCommand,
)
from app.application.dto.export_dtos import (
    PoliticaExportacionRevision,
    ExportacionPreparadaDTO,
    PipelineActividadResultDTO,
    ExportarMatricesResultDTO,
)
from app.application.export_acl import (
    ExportACL,
    ExportDataset,
)
from app.application.word_acl import (
    WordACL,
    WordActividadDTO,
    WordEstamentoItemDTO,
    WordEvidenciaItemDTO,
    WordWeeklyReportDataset,
    FuenteCifras,
    FuenteResultados,
    PoliticaPresentacionRevisionWord,
)
from app.application.ports import (
    IWordActividadRenderer,
    IWordInformeSemanalRenderer,
    IWordDossierRenderer,
)
from app.application.fakes import (
    InMemoryActividadRepository,
    InMemoryPersonaRepository,
    InMemoryParticipacionRepository,
    InMemoryEvidenciaRepository,
    InMemoryInformeSemanalRepository,
    InMemoryDiscrepanciaRepository,
    InMemoryUnitOfWork,
)
from app.application.use_cases import (
    RegistrarActividadUseCase,
    AsignarPlanificacionUseCase,
    AsignarDisenoMetodologicoUseCase,
    RegistrarInformeActividadUseCase,
    RegistrarPersonaUseCase,
    RegistrarParticipacionIndividualUseCase,
    IngestarListaAsistenciaUseCase,
    EnrutarParticipacionesActividadUseCase,
    EvaluarCalidadActividadUseCase,
    ConsultarDiscrepanciasPendientesUseCase,
    ResolverRevisionDiscrepanciaUseCase,
    ProcesarPipelineActividadUseCase,
    ExportarMatricesActividadUseCase,
    ExportarMatricesPeriodoUseCase,
    ActividadNoEncontradaError,
    GenerarInformeActividadWordUseCase,
    GenerarInformeSemanalWordUseCase,
    GenerarDossierConsolidadoWordUseCase,
)

__all__ = [
    # Commands
    "RegistrarActividadCommand",
    "AsignarPlanificacionCommand",
    "AsignarDisenoMetodologicoCommand",
    "RegistrarInformeActividadCommand",
    "RegistrarPersonaCommand",
    "RegistrarParticipacionIndividualCommand",
    "IngestarListaAsistenciaCommand",
    "RegistrarEvidenciaDigitalCommand",
    "VincularEvidenciaActividadCommand",
    "DesvincularEvidenciaActividadCommand",
    "CrearInformeSemanalCommand",
    "AsociarActividadesInformeSemanalCommand",
    "RegistrarDiscrepanciaCommand",
    "ResolverRevisionDiscrepanciaCommand",
    "EvaluarCalidadActividadCommand",
    "EjecutarPipelineActividadCommand",
    "ExportarMatricesActividadCommand",
    "ExportarMatricesPeriodoCommand",
    # Queries
    "ConsultarActividadesPorPeriodoQuery",
    "ObtenerDetalleActividadQuery",
    "BuscarPersonasPorNombreQuery",
    "ObtenerPersonaPorIdQuery",
    "ConsultarParticipantesPorActividadQuery",
    "ConsultarParticipantesEnRevisionQuery",
    "ConsultarEvidenciasActividadQuery",
    "ConsultarInformeSemanalPorPeriodoQuery",
    "ConsultarDiscrepanciasPendientesQuery",
    # DTOs
    "FilaParticipanteIngestaDTO",
    "PartidaPresupuestariaDTO",
    "DetalleActividadInformeDTO",
    "IngestaListaAsistenciaResultDTO",
    "ActividadResumenDTO",
    "ActividadDetalleDTO",
    "PersonaResumenDTO",
    "PersonaDetalleDTO",
    "ParticipacionDetalleDTO",
    "EvidenciaVinculadaDTO",
    "DiscrepanciaDetalleDTO",
    "InformeSemanalCompletoDTO",
    "PlanificacionAsignadaDTO",
    "DisenoMetodologicoAsignadoDTO",
    "InformeActividadRegistradoDTO",
    "ValidationFindingDTO",
    "QualityAssessmentDTO",
    "PoliticaExportacionRevision",
    "ExportacionPreparadaDTO",
    "PipelineActividadResultDTO",
    "ExportarMatricesResultDTO",
    # Export ACL
    "ExportACL",
    "ExportDataset",
    # Word ACL
    "WordACL",
    "WordActividadDTO",
    "WordEstamentoItemDTO",
    "WordEvidenciaItemDTO",
    "WordWeeklyReportDataset",
    "FuenteCifras",
    "FuenteResultados",
    "PoliticaPresentacionRevisionWord",
    # Ports
    "IWordActividadRenderer",
    "IWordInformeSemanalRenderer",
    "IWordDossierRenderer",
    # Fakes
    "InMemoryActividadRepository",
    "InMemoryPersonaRepository",
    "InMemoryParticipacionRepository",
    "InMemoryEvidenciaRepository",
    "InMemoryInformeSemanalRepository",
    "InMemoryDiscrepanciaRepository",
    "InMemoryUnitOfWork",
    # Use Cases
    "RegistrarActividadUseCase",
    "AsignarPlanificacionUseCase",
    "AsignarDisenoMetodologicoUseCase",
    "RegistrarInformeActividadUseCase",
    "RegistrarPersonaUseCase",
    "RegistrarParticipacionIndividualUseCase",
    "IngestarListaAsistenciaUseCase",
    "EnrutarParticipacionesActividadUseCase",
    "EvaluarCalidadActividadUseCase",
    "ConsultarDiscrepanciasPendientesUseCase",
    "ResolverRevisionDiscrepanciaUseCase",
    "ProcesarPipelineActividadUseCase",
    "ExportarMatricesActividadUseCase",
    "ExportarMatricesPeriodoUseCase",
    "ActividadNoEncontradaError",
    "GenerarInformeActividadWordUseCase",
    "GenerarInformeSemanalWordUseCase",
    "GenerarDossierConsolidadoWordUseCase",
]
