"""
app.word_consolidator.institutional_docx

Módulo del Maquetado Visual DOCX Institucional para el Producto B
(Informe Semanal Ejecutivo del Mecanismo Institucional BICU).
Fase 16.4.
"""

from app.word_consolidator.institutional_docx.constants import (
    PAGE_ORIENTATION,
    PAGE_WIDTH_PT,
    PAGE_HEIGHT_PT,
    MARGIN_TOP_PT,
    MARGIN_BOTTOM_PT,
    MARGIN_LEFT_PT,
    MARGIN_RIGHT_PT,
    COLOR_PRIMARY_BLUE,
    COLOR_ACCENT_MAGENTA,
    COLOR_WHITE,
    COLOR_BLACK,
    COLOR_BORDER_GRID,
    FONT_DOC_TITLE,
    FONT_TABLE_HEADER,
    FONT_TABLE_BODY,
    FONT_EVIDENCES_TITLE,
    FONT_ACTIVITY_HEADING,
    GRID_COLUMNS_TWIPS,
    TOTAL_TABLE_WIDTH_TWIPS,
    HEADER_DEPTO_LABEL,
    HEADER_MES_LABEL,
    HEADER_SEMANA_LABEL,
    SUPERHEADER_ACTIVIDAD,
    SUPERHEADER_RESULTADOS,
    SUPERHEADER_PROTAGONISTAS,
    SUBHEADERS_TEXTOS,
)
from app.word_consolidator.institutional_docx.spec import (
    ModoFuenteDatosEnum,
    TipoFilaEnum,
    VMergeType,
    CellMergeSpec,
    CellVisualSpec,
    CellLayoutSpec,
    RowLayoutSpec,
    TableLayoutSpec,
    EvidenciaItemSpec,
    EvidenciasActividadSpec,
    EvidenciasSectionSpec,
    InstitutionalDocxSpec,
    build_table_layout_spec,
    build_evidencias_spec,
    build_document_layout_spec,
)

__all__ = [
    # Constantes
    "PAGE_ORIENTATION",
    "PAGE_WIDTH_PT",
    "PAGE_HEIGHT_PT",
    "MARGIN_TOP_PT",
    "MARGIN_BOTTOM_PT",
    "MARGIN_LEFT_PT",
    "MARGIN_RIGHT_PT",
    "COLOR_PRIMARY_BLUE",
    "COLOR_ACCENT_MAGENTA",
    "COLOR_WHITE",
    "COLOR_BLACK",
    "COLOR_BORDER_GRID",
    "FONT_DOC_TITLE",
    "FONT_TABLE_HEADER",
    "FONT_TABLE_BODY",
    "FONT_EVIDENCES_TITLE",
    "FONT_ACTIVITY_HEADING",
    "GRID_COLUMNS_TWIPS",
    "TOTAL_TABLE_WIDTH_TWIPS",
    "HEADER_DEPTO_LABEL",
    "HEADER_MES_LABEL",
    "HEADER_SEMANA_LABEL",
    "SUPERHEADER_ACTIVIDAD",
    "SUPERHEADER_RESULTADOS",
    "SUPERHEADER_PROTAGONISTAS",
    "SUBHEADERS_TEXTOS",
    # Especificaciones y tipos
    "ModoFuenteDatosEnum",
    "TipoFilaEnum",
    "VMergeType",
    "CellMergeSpec",
    "CellVisualSpec",
    "CellLayoutSpec",
    "RowLayoutSpec",
    "TableLayoutSpec",
    "EvidenciaItemSpec",
    "EvidenciasActividadSpec",
    "EvidenciasSectionSpec",
    "InstitutionalDocxSpec",
    # Constructores
    "build_table_layout_spec",
    "build_evidencias_spec",
    "build_document_layout_spec",
]
